### ISSUE TITLE
Innova Logistic 

### ISSUE THREAD

**Issue by seydouyara** [tink-crypto/tink-java-apps#2]
**Help us help you**

We'd like to know more about
[your Tink deployment](https://docs.google.com/forms/d/1mhHvyNJQgTXFDnqOermB7-BD8GQSyvtFPUAhILRbYcA/).

**Describe the bug:**

Provide a clear and concise description of the bug.

**What was the expected behavior?**

Describe what you expected to happen.

**How can we reproduce the bug?**

Include buildable code snippets or gists which triggered the bug.

**Do you have any debugging information?**

If applicable, include error messages, stack traces, or any other debugging information.

**What version of Tink are you using?**

For example, 1.2.0.

**Can you tell us more about your development environment?**

Such as JDK 8, Python3.7, iPhone 11, or Android M.

**Is there anything else you'd like to add?**

Provide any additional context about the problem.

**Comment by tholenst** [comment]
This seems to be mistakenly filed. Please add context in the bug report in case this is not the case.
